#   Resi - Booking Tiket Bioskop    #

def main():
    
    print("================================================")
    print("                Cinegaje Bioskop                ")
    print("------------------------------------------------")
    print(" Detail Transaction     DD-MM-YYYY WIB/WIT/WITA ")
    print("                                                ")
    print(" ------------------                             ")
    print(" |                |  Fast X                     ")
    print(" |                |                             ")
    print(" |                |  Date: Thursday,DD-MM-YYYY  ")
    print(" |                |  Time: 10:00 WIB/WIT/WITA   ")
    print(" |                |                             ")
    print(" |                |                             ")
    print(" |                |  Booking Code: 9432940      ")
    print(" |                |                             ")
    print(" |                |                             ")
    print(" |                |                             ")
    print(" ------------------                             ")
    print("                                                ")
    print(" Transaction Ref :   Cinegaje/RES/DD-YYYY/8349  ")
    print(" Seats           :   A11                        ")
    print(" Tipe Bioskop    :   Reguler/Deluxe 4DX Premium ")
    print(" Total Tickets   :   5                          ")
    print(" Ticket Price    :   Rp100.000,00               ")
    print(" Promo/Diskon    :   Rp0                        ")
    print(" Payment         :   GOPAY/OVO/BCA/TUNAI/KREDIT ")
    print("                                                ")
    print(" Total Payment   :   Rp100.000,00               ")
    print("                                                ")
    print("                                                ")
    print("              ==Selamat Menonton==              ")
    print("                    ==Enjoy==                   ")
    print("                                                ")
    print("================================================")
    
if __name__ == '__main__':    
    main()   