print(f"\033[1;36m" + "==============================================================")
print(f"|               🎬 CINEMA XXI - TIKET RESMI 🎬               |")
print(f"|----------------------------------------------------------|   ")
print(f"| 🎞️\t Film\t Dilan 1991                                 |") 
print(f"| 🏢\tDate\t07-06-2025                                    |")
print(f"| 🏢\Time\t19:00                                          |")
print(f"| 🪑\tKursi\tE14                                          |")
# print(f"| 🏢\tStudio\tStudio 5                                     |")
print(f"| 🕒\tWaktu\tSabtu, 7 Juni 2025 - 21:00                   |")
print(f"| 💳\tHarga\tRp 60,000                                  |")
print(f"|----------------------------------------------------------|  ")
print(f"|        📌 Tunjukkan tiket ini saat memasuki studio         |")
print(f"==============================================================" + "\033[0m")